### ISSUE TITLE
capture byte array as string

### ISSUE THREAD

**Issue by ScubaScott** [ScubaScott/Arduino-Bluetooth#1]
having some trouble with this piece:

> ble_do_events();
>    if ( ble_available() )
>   {
>     String Scmd = "";
>     while(ble_available())
>     {
>       byte cmd;
>       cmd = ble_read();
>       Scmd.concat(cmd);
>     }
>       // Parse data here
>       Serial.println("CMD:" + Scmd);

the byte array retured from ble_read() is fine, but when it converts to string I get the numeric ascii numbers instead of the text.

**Comment by curlyk** [comment]
Change it from byte cmd to char cmd. That'll do it.

**Comment by ScubaScott** [comment]
Thanks!
